src/hrtf/tools.h
If you would rather leave it as const void *base, then we can change the tools.c declaration to be void instead of char. Either way, the method declarations weren't matching up and causing a compilation problem.
=> Fixed compilation problem when building libmysofa.a

src/hdf/dataobject.c, src/hrtf/cache.c, src/hrtf/easy.c, src/hrtf/tools.c
In the method mysofa_open, the filterlength parameter was never getting set so I added a line of code so that it gets set before the method returns. I also changed _strdup to strdup since _strdup does not exist in Linux despite Visual C's warning that you should use _strdup instead of strdup. With these changes, libmysofa seems to be working fine on Linux machines.
=> Fixed filter length parameter not getting filled in mysofa_open

README.md, src/hrtf/cache.c
State in the documentation that appropriate synchronisation mechanisms
must be used in the calling functions.
=> cache: remove pthread mutexes

src/CMakeLists.txt
Using the hardcoded .a file path there results in two major problems:
You are forced to build in the provided build dir, nowhere else works, no out of tree builds, no in-source build, no diffrently named build dir.
Additionally, not using the target for linking results in a missing dependency on it, so a plain make fails, because it tried to build mysofa2json first, before the static library is created or even built.
Just putting the mysofa-static target name there will make cmake figure out the correct .a path, and will set an appropriate dependency to ensure make builds things in order.
=> Link against mysofa-static library instead of hardcoded .a path

src/.dir-locals.el
this is a simple [emacs per-dir configuration](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) to set the indentation to <kbd>Tab</kbd>.
probably a better alternative might be to use [EditorConfig](http://editorconfig.org/), which is *cross-editor*....
=> indentation rules for emacs

tests/compare.sh
/bin/bash is not guaranteed to exist on non-GNU systems, which may
place bash in /usr/local/bin or may not provide it at all. This
script does not use any bash-specific features, so the easiest
solution here is to simply use /bin/sh, which is ubiquitous on
Unix.
=> Use /bin/sh instead of /bin/bash in tests

README.md
explicitly init mysofa_easy as NULL to avoid segfault in mysofa_close
(see https://stackoverflow.com/questions/35181909/segmentation-fault-on-pointer-null-check)
=> modified lib usage example in readme

src/hrtf/lookup.c, src/hrtf/mysofa.h, src/hrtf/neighbors.c
PR aim at reducing lookup creation (upon opening) time for:
*  measurement grids with holes (whole sections where there is no need to iterate to find a neighbor)
* Horizontal measurement grids with only azim (phi) and radius changes (e.g. loading time dropped from 3s to 0.8s by restricting the search to phi_low < .. < phi_high values)
Code-wise, the PR simply removed all differences between radius, theta, and phi search algorithms. It may be that I misjudged the importance of these differences in the first place. You're welcome to ignore this PR then.
=> Uniformisation of neighbor lookup creation for all three dimensions (radius, theta, phi)

CMakeLists.txt, src/CMakeLists.txt
Install paths are not the same on all systems. For example, some
Linux distributions use $prefix/lib64 for x86_64 libraries.
=> cmake: use GNU install paths

src/CMakeLists.txt
PROJECT_SOURCE_DIR points to the source dir of the most recent project() call, while CMAKE_SOURCE_DIR points to the top-level project.
=> allow to build project as a cmake subdirectory

README.md, src/hrtf/easy.c, src/hrtf/mysofa.h, src/hrtf/neighbors.c
Added both a manual definition of neighbors search angle/radius step to the API (no breaking changes), and an auto-skip of said search if min/max values of search grid are the same (zeroed-out dimension). 
The revised version allows to decrease loading time for exotic SOFA files (when users know what they are doing), e.g. from 1200ms to 200ms for a grid with no elevation and lots of azim and dist points.
Do let me know what you think.
=> Optimize Neighbor search for exotic scenario 

src/hrtf/interpolate.c
Found when debugging http://trac.ffmpeg.org/ticket/7632
=> fix mysofa_interpolate when interpolation is not needed

src/hrtf/neighbors.c
This commit corrects (undo) previous attempt at optimizing the
neighbor (see commit f5264b730a9dd74f91cbf08628be607d156211d0).
This optimized version would not search for neighbors beyond max and
min (overall) theta/phi values, hence not finding e.g. 0° as a
neighbor of 345° for the LISTEN HRIR database (15° steps).
=> Extended angular neighbour search to 'close the sphere'

README.md, src/hrtf/easy.c, src/hrtf/mysofa.h
Allows to bypass the linear interpolation and access nearest neighbour filters
=> added and exposed mysofa_getfilter_float_nointerp method

src/hrtf/check.c, src/hrtf/kdtree.c, src/hrtf/kdtree.h, src/hrtf/lookup.c
My goal is to completely avoid allocations in `mysofa_lookup()` at some point.
As a first step, to get a better overview, I started removing dead code, and it turns out there's a lot of it.
=> Remove dead code

src/hrtf/check.c, src/hrtf/kdtree.c, src/hrtf/kdtree.h, src/hrtf/lookup.c
This should get rid of all dynamic allocations in `mysofa_lookup()`.
=> Limit KD-Tree to exactly 3 dimensions

src/CMakeLists.txt
Fixes #109
Build fails with CMake 3.13 and later. This fixes the issue.
Tested in Arch Linux x86_64 with CMake 3.16.4 and gcc/gcov 9.2.1.
=> Fix coverage build with CMake 3.13 and later

src/CMakeLists.txt
The linking should be of the `PUBLIC` type, otherwise we will get
errors like 'undefined reference to __gcov_merge_add' when using
the library with other applications.
=> Fix undefined references to gcov symbols in the library

CMakeLists.txt
Hi!
Here are two patches from pkgsrc.
The relative paths are inconvenient if you are not using a "build" subdirectory as your build directory but some other path.
Thanks.
=> pkgsrc fixes

CMakeLists.txt, src/CMakeLists.txt
In this case the binaries will be linked with the shared object.
This will be the default for Fedora/RHEL/CentOS package
Also add -lm for linking binaries or the compilation fails.
Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>
=> Add support for building with static library disabled

.travis.yml, CMakeLists.txt
Build proper release binaries by default
Because `-fprofile-arcs` introduces non-determinism via
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96970
and release binaries should not be instrumented like this anyway.
This change makes life easier for distribution packagers.
This PR was done while working on reproducible builds for openSUSE.
=> Build proper release binaries by default

src/CMakeLists.txt
Otherwise, it could suffer compilation issues when cross-compiling (I'm compiling library for `PSP`)
```
make 
Scanning dependencies of target mysofa-static
[  4%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/reader.c.obj
cc1: error: cannot generate position-independent code for ‘-mabi=eabi’
make[2]: *** [src/CMakeFiles/mysofa-static.dir/hrtf/reader.c.obj] Error 1
make[1]: *** [src/CMakeFiles/mysofa-static.dir/all] Error 2
make: *** [all] Error 2
```
Thanks
=> Enable POSITION_INDEPENDENT_CODE just when BUILD_SHARED_LIBS is on

.appveyor.yml
I noticed the platform toolset was updated to VS 2022, but it caused Appveyor build to fail because [it was still using/expecting VS 2019](https://ci.appveyor.com/project/3DJ/libmysofa/builds/44966607):
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): 
error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. 
To build using the v143 build tools, please install v143 build tools.  
Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, 
and then selecting "Retarget solution". [C:\projects\libmysofa\windows\libmysofa.vcxproj]
```
So specifying the VS 2022 image in .appveyor.yml [fixed the …
=> Update image to Visual Studio 2022 to fix Appveyor build

README.md, src/hdf/dataobject.c
Hello @hoene,
I was testing the latest version of libmysofa, and it isn't building with CMake. There's one commit in particular that's causing it to not build (7aa1a10) in src/hrtf/dataobject.c, so I've opened this PR that reverts the changes.
=> Minor fixes 

.gitignore, src/CMakeLists.txt, src/hrtf/reader.c, windows/libmysofa.vcxproj
It's a good practice to keep generated files in a build directory. This patch move generated files so that source directory is not modified during the build.
=> cmake: generate files in the build directory

src/hrtf/easy.c
Fixes #196 
Example of workaround currently in place (from [pipewire](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/fd03f95a3eac754bdefe290fa053f2b2ea16fea2/src/modules/module-filter-chain/builtin_plugin.c#L876-886)):
```c
int ret = MYSOFA_OK; // <- if this is not previously set to MYSOFA_OK...
pthread_mutex_lock(&libmysofa_mutex);
impl->sofa = mysofa_open_cached(filename, SampleRate, &impl->n_samples, &ret);
pthread_mutex_unlock(&libmysofa_mutex);
if (ret != MYSOFA_OK) { // <- this will fail
pw_log_error("Unable to load HRTF from %s: %d %m", filename, ret);
errno = ENOENT;
return NULL;
}
```
=> Fix uninitialized error code in mysofa_open_cached

src/hrtf/reader.c
Since [f4ba5014d3202f3ecd1715e3cc8265bd9ed5585d](https://github.com/hoene/libmysofa/commit/f4ba5014d3202f3ecd1715e3cc8265bd9ed5585d), the unit test 'external' fails with the message
`libmysofa/src/tests/check_data.c:50  - CU_FAIL_FATAL("Error reading data.")`
This is caused by the check in mysofa_seek (reader.c)
`if(offset < 0 || offset >= reader->memory_len) {`
However, the call `mysofa_seek(reader, 0, SEEK_END)` (used, e.g., in `superblockRead2or3()`) invariably results in  `offset == reader->memory_len`, which appears to be correct for the end-of-file position.
Therefore I think the error check should be
`if(offset < 0 || offset > reader->memory_len) {`.
With that all unit tests are passing locally (tested on Linux and MacOS).
=> Fix offset check in mysofa_seek when used in memory mode.

CMakeLists.txt, README.md, mysofaConfig.cmake.in, src/CMakeLists.txt
This pull request adds exported CMake targets to libmysofa, making usage from other CMake-based projects easier.
The implementation follows the guide https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html .
Added build and usage instructions to the README, please adjust or ask for amendments where needed.
Also, please change or advise on naming (e.g., the project name (mysofa) and namespace name for the exported targets (mysofa::), whether it should be capitalized, ...
Note that the change adds new files in to generated packages (e.g., .deb), this would need to be communicated to package maintainers.
=> Implement CMake target exporting.

src/hrtf/portable_endian.h
The BSDs have been rather unified with regards to these naming conventions within the past 9 years. Related to #211.
```
[90% 40/43] /usr/local/libexec/ccache/cc  -I/wrkdirs/usr/ports/audio/libmysofa/work/.build/src -I/wrkdirs/usr/ports/audio/libmysofa/work/libmysofa-1.3.2/src/hrtf -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -Wall -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG -std=gnu99 -fPIC -MD -MT src/CMakeFiles/mysofa-static.dir/hrtf/reader.c.o -MF src/CMakeFiles/mysofa-static.dir/hrtf/reader.c.o.d -o src/CMakeFiles/mysofa-static.dir/hrtf/reader.c.o -c /wrkdirs/usr/ports/audio/libmysofa/work/libmysofa-1.3.2/src/hrtf/reader.c
In file included from /wrkdirs/usr/ports/audio/libmysofa/work/libmysofa-1.3.2/src/hrtf/reader.c:18: …
```
=> Fix warnings and potential linking errors on FreeBSD and DragonFly

tests/compare.sh, tests/compareIgnoreNew.sh
I encountered failed tests when building locally. This was because the project was located under a path that included spaces. This should be fixed here by wrapping the respective path in quotation marks.
=> Fix to accept spaces in paths of test scripts

src/CMakeLists.txt, src/hrtf/mysofa.h
Hi there! I'm trying to get libmysofa added to vcpkg so it will be available to more users. Also steam-audio uses libmysofa and I'd like to use steam-audio from vcpkg :smile:
See: https://github.com/microsoft/vcpkg/pull/38368
For my vcpkg port I ran into an interesting problem that this patch addresses. Without this any downstream project that depends on libmysofa will fail to properly link to the library on windows. Not sure if this is the way you'd like to fix this. We could also do a .def file for the linker to mark these functions as part of the export .lib.
=> Adding declspec export attribute to header functions

src/hrtf/portable_endian.h
Fixes build failure on illumos as per https://us-central.manta.mnx.io/pkgsrc/public/reports/upstream-trunk/20241102.2249/libmysofa-1.3.3/build.log
=> Support illumos.

README.md
I noticed this project in my updates because it had a funny name, and I decided to go visit the upstream page. Then I saw that your README could do with a bit of touching-up. Take it or leave it, I still think the name is cool, though.
=> README: use highlighted code blocks.

CMakeLists.txt, src/CMakeLists.txt, tests/compare.sh, tests/compareIgnoreNew.sh
Use the [cmake-generator-expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html) to obtain the path of [mysofa2json](https://github.com/hoene/libmysofa/blob/dd315a8ec1fee7193d40e4a59b12c5590a4a918c/src/CMakeLists.txt#L171) used by [compare.sh](https://github.com/hoene/libmysofa/blob/dd315a8ec1fee7193d40e4a59b12c5590a4a918c/tests/compare.sh) and [compareIgnoreNew.sh](https://github.com/hoene/libmysofa/blob/dd315a8ec1fee7193d40e4a59b12c5590a4a918c/tests/compareIgnoreNew.sh).
This closes #236
=> Don't use hardcoded path in test scripts.
